name 'example42-rhcs'
version '2.0.12'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-rhcs'
summary 'Puppet module for rhcs'
description 'This module installs and manages rhcs. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
